version: '3.9'
services:
  db:
    image: postgres:16
    container_name: app_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: venezadb
    networks:
      sga_veneza:
networks:
  sga_veneza:
